# Generated by Django 5.2.1 on 2025-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Felix_ITs', '0002_felix_class_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felix_class',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
