# Generated by Django 5.2.1 on 2025-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Felix_ITs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='felix_class',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
